version: "3.9"

services:
  # PHP + Laravel
  php-app:
    build: .
    container_name: php-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    expose:
      - "9000"
    depends_on:
      - mysql-db

  # Nginx Web Server
  nginx-web:
    image: nginx:alpine
    container_name: nginx-web
    ports:
      - "8088:80"   # localhost:8088
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app

  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""        # root không mật khẩu
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: mydb
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3307:3306"   # tránh xung đột với MySQL cài sẵn
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # phpMyAdmin để quản lý DB
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8889:80"   # localhost:8889
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""
      UPLOAD_LIMIT: 300M
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  db_data:
